// Mock data for On Behalf of Customer (OBO) feature

export const MOCK_CUSTOMERS = [
  {
    id: 'CUST-001',
    firstName: 'Amara',
    lastName: 'Okonkwo',
    email: 'amara.okonkwo@gmail.com',
    mobile: '+44 7700 900123',
    country: 'United Kingdom',
    active: true,
    locked: false,
    kycStatus: 'Passed',
    walletBalance: 520.00,
    walletCurrency: 'GBP',
    affiliate: 'Rhemito',
    registeredDate: '2024-03-12',
  },
  {
    id: 'CUST-002',
    firstName: 'Daniel',
    lastName: 'Mensah',
    email: 'daniel.mensah@outlook.com',
    mobile: '+44 7700 900456',
    country: 'United Kingdom',
    active: true,
    locked: false,
    kycStatus: 'Refer',
    walletBalance: 80.50,
    walletCurrency: 'GBP',
    affiliate: 'Rhemito',
    registeredDate: '2024-05-20',
  },
  {
    id: 'CUST-003',
    firstName: 'Fatima',
    lastName: 'Al-Hassan',
    email: 'fatima.alhassan@yahoo.com',
    mobile: '+44 7700 900789',
    country: 'United Kingdom',
    active: true,
    locked: true,
    kycStatus: 'Selfie Pending',
    walletBalance: 0,
    walletCurrency: 'GBP',
    affiliate: 'BasketMouth',
    registeredDate: '2024-07-08',
  },
  {
    id: 'CUST-004',
    firstName: 'James',
    lastName: 'Osei',
    email: 'james.osei@hotmail.com',
    mobile: '+44 7700 900321',
    country: 'United Kingdom',
    active: false,
    locked: false,
    kycStatus: 'Failed',
    walletBalance: 0,
    walletCurrency: 'GBP',
    affiliate: 'Sika',
    registeredDate: '2024-02-14',
  },
  {
    id: 'CUST-005',
    firstName: 'Ngozi',
    lastName: 'Adeyemi',
    email: 'ngozi.adeyemi@gmail.com',
    mobile: '+44 7700 900654',
    country: 'United Kingdom',
    active: true,
    locked: false,
    kycStatus: 'Not Done',
    walletBalance: 0,
    walletCurrency: 'GBP',
    affiliate: 'Rhemito',
    registeredDate: '2025-01-03',
  },
  {
    id: 'CUST-006',
    firstName: 'Emmanuel',
    lastName: 'Boateng',
    email: 'e.boateng@gmail.com',
    mobile: '+44 7700 900987',
    country: 'United Kingdom',
    active: true,
    locked: false,
    kycStatus: 'Passed',
    walletBalance: 1200.00,
    walletCurrency: 'GBP',
    affiliate: 'FastPay',
    registeredDate: '2023-11-22',
  },
];

export const AFFILIATES = ['Rhemito', 'BasketMouth', 'Sika', 'FastPay', 'GlobalSend'];

export const MOCK_RECIPIENTS = [
  {
    id: 'REC-001',
    firstName: 'Chukwuemeka',
    lastName: 'Okafor',
    nickname: 'Uncle Emeka',
    bank: 'First Bank of Nigeria',
    accountNumber: '3012345678',
    accountHolder: 'Chukwuemeka Okafor',
    mobile: '+234 803 123 4567',
    country: 'Nigeria',
    currency: 'NGN',
    relationship: 'Family',
    reason: 'Family Support',
    method: 'Direct to bank',
    lastUsed: '2025-03-10',
  },
  {
    id: 'REC-002',
    firstName: 'Blessing',
    lastName: 'Okonkwo',
    nickname: 'Sis Blessing',
    bank: 'Zenith Bank',
    accountNumber: '2098765432',
    accountHolder: 'Blessing Okonkwo',
    mobile: '+234 806 987 6543',
    country: 'Nigeria',
    currency: 'NGN',
    relationship: 'Sibling',
    reason: 'Education',
    method: 'Direct to bank',
    lastUsed: '2025-02-22',
  },
  {
    id: 'REC-003',
    firstName: 'Kofi',
    lastName: 'Mensah',
    nickname: 'Kofi',
    bank: 'GCB Bank',
    accountNumber: '1234567890',
    accountHolder: 'Kofi Mensah',
    mobile: '+233 244 123 456',
    country: 'Ghana',
    currency: 'GHS',
    relationship: 'Friend',
    reason: 'Business',
    method: 'SWIFT',
    lastUsed: '2025-01-15',
  },
  {
    id: 'REC-004',
    firstName: 'Aisha',
    lastName: 'Mohammed',
    nickname: 'Aisha',
    bank: 'United Bank for Africa',
    accountNumber: '4056781234',
    accountHolder: 'Aisha Mohammed',
    mobile: '+234 815 456 7890',
    country: 'Nigeria',
    currency: 'NGN',
    relationship: 'Friend',
    reason: 'Personal',
    method: 'Direct to bank',
    lastUsed: '2024-12-05',
  },
  {
    id: 'REC-005',
    firstName: 'Tunde',
    lastName: 'Adeyemi',
    nickname: 'Tunde',
    bank: 'Access Bank',
    accountNumber: '0123456789',
    accountHolder: 'Tunde Adeyemi',
    mobile: '+234 701 234 5678',
    country: 'Nigeria',
    currency: 'NGN',
    relationship: 'Spouse',
    reason: 'Living Expenses',
    method: 'Direct to bank',
    lastUsed: '2024-11-18',
  },
];

export const MOCK_BANKS = [
  'Access Bank', 'First Bank of Nigeria', 'GTBank', 'Zenith Bank',
  'United Bank for Africa', 'Fidelity Bank', 'Polaris Bank', 'Stanbic IBTC',
  'Sterling Bank', 'Union Bank', 'Wema Bank', 'FCMB',
  'GCB Bank', 'Ecobank', 'Standard Chartered', 'Barclays',
];

export const MOCK_EXCHANGE_RATES = {
  'GBP-NGN': 1902.50,
  'GBP-GHS': 17.80,
  'GBP-KES': 171.20,
  'GBP-INR': 107.40,
  'GBP-USD': 1.27,
  'GBP-EUR': 1.17,
  'USD-NGN': 1498.00,
  'EUR-NGN': 1624.00,
};

export const MOCK_FEES = {
  'Bank Deposit': { fixed: 1.99, percent: 0.5 },
  'Mobile Money': { fixed: 0.99, percent: 0.8 },
};

export const RELATIONSHIPS = [
  'Spouse', 'Parent', 'Child', 'Sibling', 'Family', 'Friend', 'Business Partner', 'Employee', 'Other',
];

export const TRANSFER_REASONS = [
  'Family Support', 'Education', 'Medical', 'Living Expenses', 'Business', 'Personal', 'Property', 'Investment', 'Other',
];

export const COUNTRIES = [
  'United Kingdom', 'Nigeria', 'Ghana', 'Kenya', 'India', 'United States',
  'Canada', 'Australia', 'Germany', 'France', 'Italy', 'Spain',
];

export const GENDERS = ['Male', 'Female', 'Other', 'Prefer not to say'];

export const KYC_STATUS_CONFIG = {
  Passed: { color: '#16a34a', bg: '#dcfce7', label: 'Passed' },
  Refer: { color: '#d97706', bg: '#fef3c7', label: 'Refer' },
  'Selfie Pending': { color: '#2563eb', bg: '#dbeafe', label: 'Selfie Pending' },
  Failed: { color: '#dc2626', bg: '#fee2e2', label: 'Failed' },
  'Not Done': { color: '#6b7280', bg: '#f3f4f6', label: 'Not Done' },
};
